<nav class="navbar navbar-inverse navbar-fixed-top navHover">
  <div class="container-fluid">
  
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.php"><p>Miaou Project</p></a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">

      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="active"><a href="#">Chat</a></li>
        <li><a href="#about">A propos</a></li>
        <li><a href="#contact">Contact</a></li>
        <li><button type="button" class="btn btn-warning navbar-btn" data-toggle="modal" data-target="#modal-login">Connexion</button></li>
      </ul>
    </div>
  </div>
</nav>


<?php require('apps/login.php'); ?>
<?php require('apps/register.php'); ?>