<nav class="navbar navbar-inverse navbar-fixed-top navHover">
  <div class="container-fluid">
  
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <span><a class="navbar-brand" href="index.php"><p>Tickets Team3</p></a></span>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-left">
        <li class="active"><a href="#">Chat</a></li>
        <li><a href="#about">A propos</a></li>
        <li><a href="#contact">Contact</a></li> 
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><p class="navbar-text">Bienvenue <b><?=htmlentities($_SESSION['login'])?></b></p></li>
        <li>
          <form method= "post">
            <button type="submit" class="btn btn-warning navbar-btn" name="action" value="logout">Se déconnecter</button>
          </form>
        </li>
      </ul>
    </div>
  </div>
</nav>

<?php require('apps/login.php'); ?>