    <div class="container">

      <div class="main">
        <h1>Système de Chat</h1>
        <p class="lead">N'hésitez pas à vous connecter</p>


  <!-- include_once('models/Message.class.php'); -->
        <div class="display-group form-control scroll-x">
        <?php require('apps/display_message.php'); ?>
        </div>
       <?php require('apps/new_message.php'); ?>
<!--         $message = new Message();
        var_dump($message); -->
      </div>
    </div><!-- /.container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="../../dist/js/bootstrap.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>



