<div class="container">
    <div class="main row">
        <h1>Système de Chat</h1>
        <p class="lead">N'hésitez pas à vous connecter</p>
        <div class="main-wrap col-xs-12 col-md-8">
            <div class="display-group form-control" id="display-group">
                <?php require('apps/display_message.php'); ?>
            </div>
            <div>
                <?php require('apps/new_message.php'); ?>
            </div>
        </div>
        <div class="option-wrap col-xs-12 col-md-4">
            <?php require('apps/display_user.php'); ?>
        </div>
    </div>
</div>


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="../../dist/js/bootstrap.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>



