<form type="submit" method="post">
	<div class="input-group">
		<input type="textarea" class="form-control entry" autocomplete="off" autofocus maxlength="1022" onkeyup="reste(this.value);" name="content" placeholder="Entrez votre message...">
		<span class="input-group-btn">
   			<button type="submit" class="btn btn-success" name="action" value="new_message" type="button">Envoyer</button>
		</span>
	</div>
	<span id="caracteres">1022</span> Caractères restants
</form>