<form type="submit" method="post">
	<div class="input-group">
		<span class="input-group-addon glyphicon glyphicon-camera"></span>
		<input type="text" class="form-control" name="content" placeholder="Entrez votre message...">
		<span class="input-group-btn">
   			<button type="submit" class="btn btn-success" name="action" value="new_message" type="button">Envoyer</button>
		</span>
	</div>
</form>