<?php

// var_dump($_SESSION); 
// var_dump(password_hash('login1',PASSWORD_BCRYPT));
?>

<div class="modal fade" id="modal-register" tabindex="-1" role="dialog" aria-labelledby="modal-label-register">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h1 class="modal-title" id="modal-label-register">Inscription</h1>
      </div>
      <div class="modal-body">

		<form method="POST" enctype="multipart/form-data">
			<div class="form-group">
				<label for="login">Login</label>
				<input type="text" class="form-control" id="login" name="login" placeholder="Login">
			</div>
			<div class="form-group">
				<label for="password1">Mot de passe</label>
				<input type="password" class="form-control" id="password1" name="password1" placeholder="Mot de passe">
			</div>
			<div class="form-group">
				<label for="password2">Retaper votre mot de passe</label>
				<input type="password" class="form-control" id="password2" name="password2" placeholder="Retaper votre mot de passe">
			</div>
			<button type="submit" class="btn btn-success" name="action" value="register">Créer votre compte</button>
		</form>

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Fermer</button>
        <!-- <button type="button" class="btn btn-primary">Save changes</button> -->
      </div>
    </div>
  </div>
</div>
